/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.paineis;

import br.com.frames.TelaPrincipalAdm;
import br.com.frames.TelaPrincipalAdm;

/**
 *
 * @author tinho
 */
public class Credito extends javax.swing.JPanel {

   

    /**
     * Creates new form Credito
     */
    public Credito() {

        initComponents();
        valorPagoTextField.setText(x.valorTotalPagoNaCompra());
        // xxx =  x.valorTotalPagoNaCompra();

        parcelasComboBox.getSelectedItem();
        valorPagoTextField.getText();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        valorPagoTextField = new javax.swing.JTextField();
        parcelasComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        valorParceladoLabel = new javax.swing.JLabel();

        jLabel1.setText("Valor Pago em Crédito:");

        parcelasComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        parcelasComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                parcelasComboBoxMouseClicked(evt);
            }
        });
        parcelasComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parcelasComboBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("Parcelar em ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(parcelasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(valorParceladoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 49, Short.MAX_VALUE))
                    .addComponent(valorPagoTextField))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(valorPagoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parcelasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(valorParceladoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void parcelasComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_parcelasComboBoxMouseClicked
        float valorParcelado = 0, valorTotal = 0, dividido = 0;
        valorTotal = Float.parseFloat(valorPagoTextField.getText());
        dividido = Float.parseFloat(parcelasComboBox.getSelectedItem().toString());
        valorParcelado = valorTotal / dividido;
        valorParceladoLabel.setText(String.valueOf(valorParcelado));
    }//GEN-LAST:event_parcelasComboBoxMouseClicked

    private void parcelasComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parcelasComboBoxActionPerformed
        float valorParcelado = 0, valorTotal = 0, dividido = 0;
        valorTotal = Float.parseFloat(valorPagoTextField.getText());
        dividido = Float.parseFloat(parcelasComboBox.getSelectedItem().toString());
        valorParcelado = valorTotal / dividido;
        valorParceladoLabel.setText(String.valueOf(valorParcelado));
    }//GEN-LAST:event_parcelasComboBoxActionPerformed
    TelaPrincipalAdm x = new TelaPrincipalAdm();

    public String getValorPago() {
        String valorPago = valorPagoTextField.getText();

        return valorPago;

    }

    public void setValorPago(String valor) {
        valorPagoTextField.setText(valor);
    }

    public String getTotalParcela() {

        String parcelas = (String) parcelasComboBox.getSelectedItem();
        return parcelas;

    }
    public String getParcelamento() {

        String parcelas = (String) valorParceladoLabel.getText();
        return parcelas;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> parcelasComboBox;
    private javax.swing.JTextField valorPagoTextField;
    private javax.swing.JLabel valorParceladoLabel;
    // End of variables declaration//GEN-END:variables
}
