package br.com.hibernate.mapping;
// Generated 27/03/2018 12:11:49 by Hibernate Tools 4.3.1



/**
 * CadastroAdministrador generated by hbm2java
 */
public class CadastroAdministrador  implements java.io.Serializable {


     private int idcadastroAdministrador;
     private String nomeAdministrador;
     private String rgAdministrador;
     private String cpfAdministrador;
     private String telefoneAdministrador;
     private String celularAdministrador;
     private String dataNascimentoAdministrador;
     private String sexoAdministrador;
     private String enderecoAdministrador;
     private String observacaoAdministrador;
     private String emailAdministrador;
     private String senhaAdministrador;
     private int idAdministradorCadastrador;
     private byte[] imagemAdministrador;

    public CadastroAdministrador() {
    }

	
    public CadastroAdministrador(int idcadastroAdministrador, String nomeAdministrador, String rgAdministrador, String cpfAdministrador, String telefoneAdministrador, String celularAdministrador, String dataNascimentoAdministrador, String sexoAdministrador, String enderecoAdministrador, String emailAdministrador, String senhaAdministrador, int idAdministradorCadastrador, byte[] imagemAdministrador) {
        this.idcadastroAdministrador = idcadastroAdministrador;
        this.nomeAdministrador = nomeAdministrador;
        this.rgAdministrador = rgAdministrador;
        this.cpfAdministrador = cpfAdministrador;
        this.telefoneAdministrador = telefoneAdministrador;
        this.celularAdministrador = celularAdministrador;
        this.dataNascimentoAdministrador = dataNascimentoAdministrador;
        this.sexoAdministrador = sexoAdministrador;
        this.enderecoAdministrador = enderecoAdministrador;
        this.emailAdministrador = emailAdministrador;
        this.senhaAdministrador = senhaAdministrador;
        this.idAdministradorCadastrador = idAdministradorCadastrador;
        this.imagemAdministrador = imagemAdministrador;
    }
    public CadastroAdministrador(int idcadastroAdministrador, String nomeAdministrador, String rgAdministrador, String cpfAdministrador, String telefoneAdministrador, String celularAdministrador, String dataNascimentoAdministrador, String sexoAdministrador, String enderecoAdministrador, String observacaoAdministrador, String emailAdministrador, String senhaAdministrador, int idAdministradorCadastrador, byte[] imagemAdministrador) {
       this.idcadastroAdministrador = idcadastroAdministrador;
       this.nomeAdministrador = nomeAdministrador;
       this.rgAdministrador = rgAdministrador;
       this.cpfAdministrador = cpfAdministrador;
       this.telefoneAdministrador = telefoneAdministrador;
       this.celularAdministrador = celularAdministrador;
       this.dataNascimentoAdministrador = dataNascimentoAdministrador;
       this.sexoAdministrador = sexoAdministrador;
       this.enderecoAdministrador = enderecoAdministrador;
       this.observacaoAdministrador = observacaoAdministrador;
       this.emailAdministrador = emailAdministrador;
       this.senhaAdministrador = senhaAdministrador;
       this.idAdministradorCadastrador = idAdministradorCadastrador;
       this.imagemAdministrador = imagemAdministrador;
    }
   
    public int getIdcadastroAdministrador() {
        return this.idcadastroAdministrador;
    }
    
    public void setIdcadastroAdministrador(int idcadastroAdministrador) {
        this.idcadastroAdministrador = idcadastroAdministrador;
    }
    public String getNomeAdministrador() {
        return this.nomeAdministrador;
    }
    
    public void setNomeAdministrador(String nomeAdministrador) {
        this.nomeAdministrador = nomeAdministrador;
    }
    public String getRgAdministrador() {
        return this.rgAdministrador;
    }
    
    public void setRgAdministrador(String rgAdministrador) {
        this.rgAdministrador = rgAdministrador;
    }
    public String getCpfAdministrador() {
        return this.cpfAdministrador;
    }
    
    public void setCpfAdministrador(String cpfAdministrador) {
        this.cpfAdministrador = cpfAdministrador;
    }
    public String getTelefoneAdministrador() {
        return this.telefoneAdministrador;
    }
    
    public void setTelefoneAdministrador(String telefoneAdministrador) {
        this.telefoneAdministrador = telefoneAdministrador;
    }
    public String getCelularAdministrador() {
        return this.celularAdministrador;
    }
    
    public void setCelularAdministrador(String celularAdministrador) {
        this.celularAdministrador = celularAdministrador;
    }
    public String getDataNascimentoAdministrador() {
        return this.dataNascimentoAdministrador;
    }
    
    public void setDataNascimentoAdministrador(String dataNascimentoAdministrador) {
        this.dataNascimentoAdministrador = dataNascimentoAdministrador;
    }
    public String getSexoAdministrador() {
        return this.sexoAdministrador;
    }
    
    public void setSexoAdministrador(String sexoAdministrador) {
        this.sexoAdministrador = sexoAdministrador;
    }
    public String getEnderecoAdministrador() {
        return this.enderecoAdministrador;
    }
    
    public void setEnderecoAdministrador(String enderecoAdministrador) {
        this.enderecoAdministrador = enderecoAdministrador;
    }
    public String getObservacaoAdministrador() {
        return this.observacaoAdministrador;
    }
    
    public void setObservacaoAdministrador(String observacaoAdministrador) {
        this.observacaoAdministrador = observacaoAdministrador;
    }
    public String getEmailAdministrador() {
        return this.emailAdministrador;
    }
    
    public void setEmailAdministrador(String emailAdministrador) {
        this.emailAdministrador = emailAdministrador;
    }
    public String getSenhaAdministrador() {
        return this.senhaAdministrador;
    }
    
    public void setSenhaAdministrador(String senhaAdministrador) {
        this.senhaAdministrador = senhaAdministrador;
    }
    public int getIdAdministradorCadastrador() {
        return this.idAdministradorCadastrador;
    }
    
    public void setIdAdministradorCadastrador(int idAdministradorCadastrador) {
        this.idAdministradorCadastrador = idAdministradorCadastrador;
    }
    public byte[] getImagemAdministrador() {
        return this.imagemAdministrador;
    }
    
    public void setImagemAdministrador(byte[] imagemAdministrador) {
        this.imagemAdministrador = imagemAdministrador;
    }




}


