package br.com.hibernate.mapping;
// Generated 27/03/2018 12:11:49 by Hibernate Tools 4.3.1



/**
 * CadastroUsuario generated by hbm2java
 */
public class CadastroUsuario  implements java.io.Serializable {


     private int idcadastroUsuario;
     private String nomeUsuario;
     private String rgUsuario;
     private String cpfUsuario;
     private String telefoneUsuario;
     private String celularUsuario;
     private String dataNascimentoUsuario;
     private String sexoUsuario;
     private String enderecoUsuario;
     private String observacaoUsuario;
     private String emailUsuario;
     private String senhaUsuario;
     private int idAdministradorCadastroUsuario;
     private byte[] imagemUsuario;

    public CadastroUsuario() {
    }

    public CadastroUsuario(int idcadastroUsuario, String nomeUsuario, String rgUsuario, String cpfUsuario, String telefoneUsuario, String celularUsuario, String dataNascimentoUsuario, String sexoUsuario, String enderecoUsuario, String observacaoUsuario, String emailUsuario, String senhaUsuario, int idAdministradorCadastroUsuario, byte[] imagemUsuario) {
       this.idcadastroUsuario = idcadastroUsuario;
       this.nomeUsuario = nomeUsuario;
       this.rgUsuario = rgUsuario;
       this.cpfUsuario = cpfUsuario;
       this.telefoneUsuario = telefoneUsuario;
       this.celularUsuario = celularUsuario;
       this.dataNascimentoUsuario = dataNascimentoUsuario;
       this.sexoUsuario = sexoUsuario;
       this.enderecoUsuario = enderecoUsuario;
       this.observacaoUsuario = observacaoUsuario;
       this.emailUsuario = emailUsuario;
       this.senhaUsuario = senhaUsuario;
       this.idAdministradorCadastroUsuario = idAdministradorCadastroUsuario;
       this.imagemUsuario = imagemUsuario;
    }
   
    public int getIdcadastroUsuario() {
        return this.idcadastroUsuario;
    }
    
    public void setIdcadastroUsuario(int idcadastroUsuario) {
        this.idcadastroUsuario = idcadastroUsuario;
    }
    public String getNomeUsuario() {
        return this.nomeUsuario;
    }
    
    public void setNomeUsuario(String nomeUsuario) {
        this.nomeUsuario = nomeUsuario;
    }
    public String getRgUsuario() {
        return this.rgUsuario;
    }
    
    public void setRgUsuario(String rgUsuario) {
        this.rgUsuario = rgUsuario;
    }
    public String getCpfUsuario() {
        return this.cpfUsuario;
    }
    
    public void setCpfUsuario(String cpfUsuario) {
        this.cpfUsuario = cpfUsuario;
    }
    public String getTelefoneUsuario() {
        return this.telefoneUsuario;
    }
    
    public void setTelefoneUsuario(String telefoneUsuario) {
        this.telefoneUsuario = telefoneUsuario;
    }
    public String getCelularUsuario() {
        return this.celularUsuario;
    }
    
    public void setCelularUsuario(String celularUsuario) {
        this.celularUsuario = celularUsuario;
    }
    public String getDataNascimentoUsuario() {
        return this.dataNascimentoUsuario;
    }
    
    public void setDataNascimentoUsuario(String dataNascimentoUsuario) {
        this.dataNascimentoUsuario = dataNascimentoUsuario;
    }
    public String getSexoUsuario() {
        return this.sexoUsuario;
    }
    
    public void setSexoUsuario(String sexoUsuario) {
        this.sexoUsuario = sexoUsuario;
    }
    public String getEnderecoUsuario() {
        return this.enderecoUsuario;
    }
    
    public void setEnderecoUsuario(String enderecoUsuario) {
        this.enderecoUsuario = enderecoUsuario;
    }
    public String getObservacaoUsuario() {
        return this.observacaoUsuario;
    }
    
    public void setObservacaoUsuario(String observacaoUsuario) {
        this.observacaoUsuario = observacaoUsuario;
    }
    public String getEmailUsuario() {
        return this.emailUsuario;
    }
    
    public void setEmailUsuario(String emailUsuario) {
        this.emailUsuario = emailUsuario;
    }
    public String getSenhaUsuario() {
        return this.senhaUsuario;
    }
    
    public void setSenhaUsuario(String senhaUsuario) {
        this.senhaUsuario = senhaUsuario;
    }
    public int getIdAdministradorCadastroUsuario() {
        return this.idAdministradorCadastroUsuario;
    }
    
    public void setIdAdministradorCadastroUsuario(int idAdministradorCadastroUsuario) {
        this.idAdministradorCadastroUsuario = idAdministradorCadastroUsuario;
    }
    public byte[] getImagemUsuario() {
        return this.imagemUsuario;
    }
    
    public void setImagemUsuario(byte[] imagemUsuario) {
        this.imagemUsuario = imagemUsuario;
    }




}


