package br.com.hibernate.mapping;
// Generated 27/03/2018 12:11:49 by Hibernate Tools 4.3.1



/**
 * CadastroEntradaProduto generated by hbm2java
 */
public class CadastroEntradaProduto  implements java.io.Serializable {


     private int idcadastroEntradaProduto;
     private String codigoBarrasEntradaProduto;
     private String quantidadeEntradaProduto;
     private String dataValidadeEntradaProduto;
     private String fornecedorEntradaProduto;
     private String valorUnitarioEntradaProduto;
     private String localEntradaProduto;
     private String dataEntradaProduto;
     private String horaEntradaProduto;
     private int idAdministradorEntradaProduto;

    public CadastroEntradaProduto() {
    }

    public CadastroEntradaProduto(int idcadastroEntradaProduto, String codigoBarrasEntradaProduto, String quantidadeEntradaProduto, String dataValidadeEntradaProduto, String fornecedorEntradaProduto, String valorUnitarioEntradaProduto, String localEntradaProduto, String dataEntradaProduto, String horaEntradaProduto, int idAdministradorEntradaProduto) {
       this.idcadastroEntradaProduto = idcadastroEntradaProduto;
       this.codigoBarrasEntradaProduto = codigoBarrasEntradaProduto;
       this.quantidadeEntradaProduto = quantidadeEntradaProduto;
       this.dataValidadeEntradaProduto = dataValidadeEntradaProduto;
       this.fornecedorEntradaProduto = fornecedorEntradaProduto;
       this.valorUnitarioEntradaProduto = valorUnitarioEntradaProduto;
       this.localEntradaProduto = localEntradaProduto;
       this.dataEntradaProduto = dataEntradaProduto;
       this.horaEntradaProduto = horaEntradaProduto;
       this.idAdministradorEntradaProduto = idAdministradorEntradaProduto;
    }
   
    public int getIdcadastroEntradaProduto() {
        return this.idcadastroEntradaProduto;
    }
    
    public void setIdcadastroEntradaProduto(int idcadastroEntradaProduto) {
        this.idcadastroEntradaProduto = idcadastroEntradaProduto;
    }
    public String getCodigoBarrasEntradaProduto() {
        return this.codigoBarrasEntradaProduto;
    }
    
    public void setCodigoBarrasEntradaProduto(String codigoBarrasEntradaProduto) {
        this.codigoBarrasEntradaProduto = codigoBarrasEntradaProduto;
    }
    public String getQuantidadeEntradaProduto() {
        return this.quantidadeEntradaProduto;
    }
    
    public void setQuantidadeEntradaProduto(String quantidadeEntradaProduto) {
        this.quantidadeEntradaProduto = quantidadeEntradaProduto;
    }
    public String getDataValidadeEntradaProduto() {
        return this.dataValidadeEntradaProduto;
    }
    
    public void setDataValidadeEntradaProduto(String dataValidadeEntradaProduto) {
        this.dataValidadeEntradaProduto = dataValidadeEntradaProduto;
    }
    public String getFornecedorEntradaProduto() {
        return this.fornecedorEntradaProduto;
    }
    
    public void setFornecedorEntradaProduto(String fornecedorEntradaProduto) {
        this.fornecedorEntradaProduto = fornecedorEntradaProduto;
    }
    public String getValorUnitarioEntradaProduto() {
        return this.valorUnitarioEntradaProduto;
    }
    
    public void setValorUnitarioEntradaProduto(String valorUnitarioEntradaProduto) {
        this.valorUnitarioEntradaProduto = valorUnitarioEntradaProduto;
    }
    public String getLocalEntradaProduto() {
        return this.localEntradaProduto;
    }
    
    public void setLocalEntradaProduto(String localEntradaProduto) {
        this.localEntradaProduto = localEntradaProduto;
    }
    public String getDataEntradaProduto() {
        return this.dataEntradaProduto;
    }
    
    public void setDataEntradaProduto(String dataEntradaProduto) {
        this.dataEntradaProduto = dataEntradaProduto;
    }
    public String getHoraEntradaProduto() {
        return this.horaEntradaProduto;
    }
    
    public void setHoraEntradaProduto(String horaEntradaProduto) {
        this.horaEntradaProduto = horaEntradaProduto;
    }
    public int getIdAdministradorEntradaProduto() {
        return this.idAdministradorEntradaProduto;
    }
    
    public void setIdAdministradorEntradaProduto(int idAdministradorEntradaProduto) {
        this.idAdministradorEntradaProduto = idAdministradorEntradaProduto;
    }




}


