package br.com.hibernate.mapping;
// Generated 27/03/2018 12:11:49 by Hibernate Tools 4.3.1



/**
 * RelatorioDeAcesso generated by hbm2java
 */
public class RelatorioDeAcesso  implements java.io.Serializable {


     private int idrelatorioDeAcesso;
     private String dataLogado;
     private String horaLogado;
     private String tipoLogado;
     private String idLogado;

    public RelatorioDeAcesso() {
    }

    public RelatorioDeAcesso(int idrelatorioDeAcesso, String dataLogado, String horaLogado, String tipoLogado, String idLogado) {
       this.idrelatorioDeAcesso = idrelatorioDeAcesso;
       this.dataLogado = dataLogado;
       this.horaLogado = horaLogado;
       this.tipoLogado = tipoLogado;
       this.idLogado = idLogado;
    }
   
    public int getIdrelatorioDeAcesso() {
        return this.idrelatorioDeAcesso;
    }
    
    public void setIdrelatorioDeAcesso(int idrelatorioDeAcesso) {
        this.idrelatorioDeAcesso = idrelatorioDeAcesso;
    }
    public String getDataLogado() {
        return this.dataLogado;
    }
    
    public void setDataLogado(String dataLogado) {
        this.dataLogado = dataLogado;
    }
    public String getHoraLogado() {
        return this.horaLogado;
    }
    
    public void setHoraLogado(String horaLogado) {
        this.horaLogado = horaLogado;
    }
    public String getTipoLogado() {
        return this.tipoLogado;
    }
    
    public void setTipoLogado(String tipoLogado) {
        this.tipoLogado = tipoLogado;
    }
    public String getIdLogado() {
        return this.idLogado;
    }
    
    public void setIdLogado(String idLogado) {
        this.idLogado = idLogado;
    }




}


