/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.frames;

import br.com.hibernate.mapping.CadastroEntradaProduto;
import br.com.hibernate.mapping.CadastroProduto;
import org.hibernate.Session;
import br.com.hibernate.mapping.NewHibernateUtil;
import org.hibernate.Transaction;
import br.com.hibernate.mapping.CadastroRetiradaProduto;
import br.com.hibernate.mapping.RelatorioDeAcesso;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import org.hibernate.SQLQuery;

/**
 *
 * @author 0040481522037
 */
public class F10CadastroRetiradaProduto extends javax.swing.JFrame {

    /**
     * Creates new form CadastroRetiradaProduto
     */
    public F10CadastroRetiradaProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        dataValidadeProdutoTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        valorUnitarioProdutoTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        quantidadeRetiradaProdutoTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        localProdutoTextField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        codigoBarrasProdutoCadastradoTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        motivosRetiradaProdutoTextArea = new javax.swing.JTextArea();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        retiradaDeProdutoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Entrada de Produto"));

        jLabel5.setText("Data de Validade");

        jLabel8.setText("Valor Unitário");

        jLabel10.setText("Quantidade");

        jLabel11.setText("Local");

        jPanel4.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Código de Barras do Produto");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(codigoBarrasProdutoCadastradoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(codigoBarrasProdutoCadastradoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Motivos");

        motivosRetiradaProdutoTextArea.setColumns(20);
        motivosRetiradaProdutoTextArea.setRows(5);
        jScrollPane1.setViewportView(motivosRetiradaProdutoTextArea);

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(267, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addComponent(jLabel5))
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(localProdutoTextField)
                    .addComponent(valorUnitarioProdutoTextField)
                    .addComponent(dataValidadeProdutoTextField)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(quantidadeRetiradaProdutoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantidadeRetiradaProdutoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dataValidadeProdutoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(valorUnitarioProdutoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(localProdutoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setText("Cadastro de Retirada de Produtos");

        retiradaDeProdutoButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        retiradaDeProdutoButton.setText("Retirar Produto");
        retiradaDeProdutoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retiradaDeProdutoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(retiradaDeProdutoButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 51, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(retiradaDeProdutoButton)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void retiradaDeProdutoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retiradaDeProdutoButtonActionPerformed

        boolean camposNaoPreenchidos = false;
        if (quantidadeRetiradaProdutoTextField.getText().equals("")
                || dataValidadeProdutoTextField.getText().equals("")
                || valorUnitarioProdutoTextField.getText().equals("")
                || localProdutoTextField.getText().equals("")
                || motivosRetiradaProdutoTextArea.getText().equals("")) {
            camposNaoPreenchidos = true;
            JOptionPane.showMessageDialog(null, "Preencha todos os campos");
        }
        if (camposNaoPreenchidos == false) {

            Session bancoConveniencia = NewHibernateUtil.getSessionFactory().openSession();
            Transaction t = bancoConveniencia.beginTransaction();

            SQLQuery consultaRelatorio = bancoConveniencia.createSQLQuery("SELECT * FROM relatorio_de_acesso");
            consultaRelatorio.addEntity(RelatorioDeAcesso.class);
            List<RelatorioDeAcesso> relatorioAcesso = (List<RelatorioDeAcesso>) consultaRelatorio.list();

            SQLQuery consultaCadastroProduto = bancoConveniencia.createSQLQuery("select * from cadastro_produto");
            consultaCadastroProduto.addEntity(CadastroProduto.class);
            List<CadastroProduto> listaCadastroProduto = (List<CadastroProduto>) consultaCadastroProduto.list();

            CadastroRetiradaProduto cadastroRetiradaProduto = new CadastroRetiradaProduto();

            int idLogado = 0;

            SimpleDateFormat data = new SimpleDateFormat("dd-MM-yyyy");
            SimpleDateFormat hora = new SimpleDateFormat("hh:mm:ss");
            Date hoje = new Date();

            for (RelatorioDeAcesso u : relatorioAcesso) {
                idLogado = Integer.parseInt(u.getIdLogado());
            }
            boolean produtoNaoEncontrado = false;
            for (CadastroProduto u : listaCadastroProduto) {
                if (u.getCodigoBarrasProduto().equals(codigoBarrasProdutoCadastradoTextField.getText())) {
                    int x = Integer.parseInt(u.getQuantidadeProduto());
                    int y = Integer.parseInt(quantidadeRetiradaProdutoTextField.getText());
                    // 

                    int td = x - y;

                    if (td < 0) {
                        JOptionPane.showMessageDialog(null, "A quantidade da retirada excede o total no estoque");
                    } else {
                        cadastroRetiradaProduto.setCodigoBarrasRetiradaProduto(codigoBarrasProdutoCadastradoTextField.getText());
                        cadastroRetiradaProduto.setQuantidadeRetiradaProduto(quantidadeRetiradaProdutoTextField.getText());
                        cadastroRetiradaProduto.setDataValidadeRetiradaProduto(dataValidadeProdutoTextField.getText());
                        cadastroRetiradaProduto.setValorUnitarioRetiradaProduto(valorUnitarioProdutoTextField.getText());
                        cadastroRetiradaProduto.setLocalRetiradaProduto(localProdutoTextField.getText());
                        cadastroRetiradaProduto.setMotivosRetiradaProduto(motivosRetiradaProdutoTextArea.getText());
                        cadastroRetiradaProduto.setDataRetiradaProduto(data.format(hoje));
                        cadastroRetiradaProduto.setHoraRetiradaProduto(hora.format(hoje));

                        cadastroRetiradaProduto.setIdAdministradorRetiradaProduto(idLogado);

                        u.setQuantidadeProduto(String.valueOf(td));

                        bancoConveniencia.update(u);
                        bancoConveniencia.save(cadastroRetiradaProduto);
                        t.commit();
                        bancoConveniencia.close();
                        produtoNaoEncontrado = true;
                        JOptionPane.showMessageDialog(null, "Retirada de Produto Realizada com Sucesso");
                    }
                }

            }
            if (produtoNaoEncontrado == false) {
                JOptionPane.showMessageDialog(null, "Produto não encontrado");
            }
        }
    }//GEN-LAST:event_retiradaDeProdutoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F10CadastroRetiradaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F10CadastroRetiradaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F10CadastroRetiradaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F10CadastroRetiradaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F10CadastroRetiradaProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codigoBarrasProdutoCadastradoTextField;
    private javax.swing.JTextField dataValidadeProdutoTextField;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField localProdutoTextField;
    private javax.swing.JTextArea motivosRetiradaProdutoTextArea;
    private javax.swing.JTextField quantidadeRetiradaProdutoTextField;
    private javax.swing.JButton retiradaDeProdutoButton;
    private javax.swing.JTextField valorUnitarioProdutoTextField;
    // End of variables declaration//GEN-END:variables
}
