/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.frames;

import org.hibernate.Session;
import br.com.hibernate.mapping.NewHibernateUtil;
import br.com.hibernate.mapping.CadastroEntradaProduto;
import br.com.hibernate.mapping.RelatorioDeAcesso;
import java.util.List;
import org.hibernate.SQLQuery;
import org.hibernate.Transaction;
import br.com.hibernate.mapping.CadastroProduto;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author 0040481522037
 */
public class F9CadastroEntradaProduto extends javax.swing.JFrame {

    /**
     * Creates new form CadastroEntradaProduto
     */
    public F9CadastroEntradaProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        adicionarEntradaProdutoButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        validadeProdutoTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fornecedorProdutoTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        valorUnitarioProdutoTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        quantidadeEntradaProdutoTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        localProdutoTextField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        codigoBarrasProdutoCadastradoTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setText("Cadastro de Entrada de Produtos");

        adicionarEntradaProdutoButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        adicionarEntradaProdutoButton.setText("Adicionar Produto");
        adicionarEntradaProdutoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarEntradaProdutoButtonActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Entrada de Produto"));

        jLabel5.setText("Data de Validade");

        jLabel7.setText("Fornecedor");

        jLabel8.setText("Valor Unitário");

        jLabel10.setText("Quantidade");

        jLabel11.setText("Local");

        jPanel4.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Código de Barras do Produto");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(codigoBarrasProdutoCadastradoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(codigoBarrasProdutoCadastradoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel5))
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(quantidadeEntradaProdutoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(validadeProdutoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fornecedorProdutoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                            .addComponent(valorUnitarioProdutoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(localProdutoTextField)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(249, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantidadeEntradaProdutoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(validadeProdutoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fornecedorProdutoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorUnitarioProdutoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(localProdutoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(adicionarEntradaProdutoButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addGap(51, 51, 51)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(adicionarEntradaProdutoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adicionarEntradaProdutoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarEntradaProdutoButtonActionPerformed

        boolean camposNaoPreenchidos = false;
        if (quantidadeEntradaProdutoTextField.getText().equals("")
                || validadeProdutoTextField.getText().equals("")
                || valorUnitarioProdutoTextField.getText().equals("")
                || localProdutoTextField.getText().equals("")) {
            camposNaoPreenchidos = true;
            JOptionPane.showMessageDialog(null, "Preencha todos os campos");
        }
        if (camposNaoPreenchidos == false) {

            Session bancoConveniencia = NewHibernateUtil.getSessionFactory().openSession();
            Transaction t = bancoConveniencia.beginTransaction();

            SQLQuery consultaRelatorio = bancoConveniencia.createSQLQuery("SELECT * FROM relatorio_de_acesso");
            consultaRelatorio.addEntity(RelatorioDeAcesso.class);
            List<RelatorioDeAcesso> relatorioAcesso = (List<RelatorioDeAcesso>) consultaRelatorio.list();

            SQLQuery consultaCadastroProduto = bancoConveniencia.createSQLQuery("select * from cadastro_produto");
            consultaCadastroProduto.addEntity(CadastroProduto.class);
            List<CadastroProduto> listaCadastroProduto = (List<CadastroProduto>) consultaCadastroProduto.list();

            CadastroEntradaProduto cadastroDeEntrada = new CadastroEntradaProduto();

            int idLogado = 0;

            SimpleDateFormat data = new SimpleDateFormat("dd-MM-yyyy");
            SimpleDateFormat hora = new SimpleDateFormat("hh:mm:ss");
            Date hoje = new Date();

            for (RelatorioDeAcesso u : relatorioAcesso) {
                idLogado = Integer.parseInt(u.getIdLogado());
            }
            boolean produtoNaoEncontrado = false;
            for (CadastroProduto u : listaCadastroProduto) {
                if (u.getCodigoBarrasProduto().equals(codigoBarrasProdutoCadastradoTextField.getText())) {

                    //Cadastro de entrada de produto
                    cadastroDeEntrada.setCodigoBarrasEntradaProduto(codigoBarrasProdutoCadastradoTextField.getText());
                    cadastroDeEntrada.setQuantidadeEntradaProduto(quantidadeEntradaProdutoTextField.getText());
                    cadastroDeEntrada.setDataValidadeEntradaProduto(validadeProdutoTextField.getText());

                    cadastroDeEntrada.setFornecedorEntradaProduto(fornecedorProdutoTextField.getText());
                    cadastroDeEntrada.setValorUnitarioEntradaProduto(valorUnitarioProdutoTextField.getText());
                    cadastroDeEntrada.setLocalEntradaProduto(localProdutoTextField.getText());

                    cadastroDeEntrada.setDataEntradaProduto(data.format(hoje));
                    cadastroDeEntrada.setHoraEntradaProduto(hora.format(hoje));

                    cadastroDeEntrada.setIdAdministradorEntradaProduto(idLogado);

                    // Atualizacao da quantidade no cadastro do produto
                    int x = Integer.parseInt(u.getQuantidadeProduto());
                    int y = Integer.parseInt(quantidadeEntradaProdutoTextField.getText());
                    int td = x + y;
                    //u.setQuantidadeProduto(x + Integer.parseInt(quantidadeEntradaProdutoTextField.getText()));
                    //u.setCodigoBarrasProduto(String.valueOf(td));
                    u.setQuantidadeProduto(String.valueOf(td));
                    bancoConveniencia.update(u);
                    // bancoConveniencia.save(cadastroProduto);
                    bancoConveniencia.save(cadastroDeEntrada);
                    t.commit();
                    bancoConveniencia.close();
                    produtoNaoEncontrado=true;
                    JOptionPane.showMessageDialog(null, "Entrada de Produto Realizada com Sucesso");
                } 
            }
            if(produtoNaoEncontrado==false){
                 JOptionPane.showMessageDialog(null, "Produto não encontrado");
            }

        }

    }//GEN-LAST:event_adicionarEntradaProdutoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F9CadastroEntradaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new F9CadastroEntradaProduto().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarEntradaProdutoButton;
    private javax.swing.JTextField codigoBarrasProdutoCadastradoTextField;
    private javax.swing.JTextField fornecedorProdutoTextField;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField localProdutoTextField;
    private javax.swing.JTextField quantidadeEntradaProdutoTextField;
    private javax.swing.JTextField validadeProdutoTextField;
    private javax.swing.JTextField valorUnitarioProdutoTextField;
    // End of variables declaration//GEN-END:variables
}
